export default {
    primary: '#fc5c65',
    secondary: '#4ecdc4',
    black: '#000',
    background: 'lightgreen',
    button: '#004D40',
    outline: 'white',
    lightText: 'white',
    darkText: 'black',
    transparent: 'rgba(0, 0, 0, 0)',
    inputBorder: '#ccc',
    inputBackground: 'white',
    highStreakBackground: 'orange',
    optionsBackground: 'grey',
    optionsMenuBackground: 'green',
    shadow: '#000',
    correct: '#4CAF50',
    incorrect: '#f44336',
    white: '#ffffff',
    correctButton: '#388E3C',
    incorrectButton: '#D32F2F',
    highStreakBox: 'orange',
    optionsBox: 'grey',
    optionsModal: "green",
    whiteSmoke: "#f5f5f5",
    optionBoxBackground: '#006400',
    highScoresSecondary: '#004D40',
    highScoresTertiary: 'green',
    unsure: 'orange',
    unsureButton: '#cc8400',
    
}